version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nomad_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nomadbike_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nomad_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: nomad_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001" # WebSockets
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

volumes:
  pgdata:
